package github

// Source: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
var languageColors = map[string]string{
	"1C Enterprise":            "#814CCC",
	"ABAP":                     "#E82C0C",
	"ActionScript":             "#882B0F",
	"Ada":                      "#02f88c",
	"Agda":                     "#315665",
	"AGS Script":               "#B9D9FF",
	"Alloy":                    "#64C800",
	"Alpine Abuild":            "#0D597F",
	"AMPL":                     "#E6EFBB",
	"AngelScript":              "#C7D7DC",
	"ANTLR":                    "#9DC3FF",
	"Apex":                     "#1797c0",
	"API Blueprint":            "#2ACCA8",
	"APL":                      "#5A8164",
	"Apollo Guidance Computer": "#0B3D91",
	"AppleScript":              "#101F1F",
	"Arc":                      "#aa2afe",
	"Arduino":                  "#bd79d1",
	"ASP.NET":                  "#9400ff",
	"Assembly":                 "#6E4C13",
	"Astro":                    "#ff5a03",
	"AutoHotkey":               "#6594b9",
	"AutoIt":                   "#1C3552",
	"Awk":                      "#c30e9b",
	"Ballerina":                "#FF5000",
	"Batchfile":                "#C1F12E",
	"Blade":                    "#f7523f",
	"BlitzMax":                 "#cd6400",
	"Boo":                      "#d4bec1",
	"Brainfuck":                "#2F2530",
	"C":                        "#555555",
	"C#":                       "#178600",
	"C++":                      "#f34b7d",
	"C2hs Haskell":             "#53b7a6",
	"Cap'n Proto":              "#c42727",
	"CartoCSS":                 "#613361",
	"Ceylon":                   "#dfa535",
	"Chapel":                   "#8dc63f",
	"Charity":                  "#613361",
	"ChucK":                    "#3f8000",
	"Cirru":                    "#ccccff",
	"Clarion":                  "#db901e",
	"Clean":                    "#3F85AF",
	"Click":                    "#E4E6F3",
	"CLIPS":                    "#00A300",
	"Clojure":                  "#db5855",
	"CMake":                    "#DA3434",
	"COBOL":                    "#90a95a",
	"CoffeeScript":             "#244776",
	"ColdFusion":               "#ed2cd6",
	"Common Lisp":              "#3fb68b",
	"Component Pascal":         "#B0CE4E",
	"Cool":                     "#915568",
	"Coq":                      "#d0b68c",
	"Crystal":                  "#000100",
	"CSS":                      "#563d7c",
	"Cucumber":                 "#5B2063",
	"Cuda":                     "#3A4E3A",
	"Cycript":                  "#925a51",
	"Cython":                   "#fedf5b",
	"D":                        "#ba595e",
	"Dart":                     "#00B4AB",
	"Diff":                     "#88dddd",
	"DIGITAL Command Language": "#F153F5",
	"DM":                       "#447265",
	"Dockerfile":               "#384d54",
	"Dogescript":               "#cca760",
	"DTrace":                   "#cc0000",
	"Dylan":                    "#6c616e",
	"E":                        "#ccce35",
	"eC":                       "#913960",
	"ECL":                      "#8a1267",
	"Eiffel":                   "#4d6977",
	"Elixir":                   "#6e4a7e",
	"Elm":                      "#60B5CC",
	"Emacs Lisp":               "#c065db",
	"EmberScript":              "#FFF4F3",
	"Erlang":                   "#B83998",
	"F#":                       "#b845fc",
	"Factor":                   "#636746",
	"Fancy":                    "#7b9db4",
	"Fantom":                   "#14253c",
	"Forth":                    "#341708",
	"Fortran":                  "#4d41b1",
	"FreeMarker":               "#0050b2",
	"Frege":                    "#d7f7fa",
	"Game Maker Language":      "#71b417",
	"GAMS":                     "#f49a22",
	"GAP":                      "#0000cc",
	"GCC Machine Description":  "#FFCF15",
	"GDB":                      "#613361",
	"GDScript":                 "#355570",
	"Genie":                    "#fb855d",
	"Genshi":                   "#951531",
	"Gentoo Ebuild":            "#9400ff",
	"Gentoo Eclass":            "#9400ff",
	"Gherkin":                  "#5B2063",
	"GLSL":                     "#5686a5",
	"Glyph":                    "#c1ac7f",
	"Gnuplot":                  "#f0a9f0",
	"Go":                       "#00ADD8",
	"Golo":                     "#88562A",
	"Gosu":                     "#82937f",
	"Grace":                    "#615f8b",
	"Gradle":                   "#02303a",
	"Grammatical Framework":    "#79aa7a",
	"Groovy":                   "#e69f56",
	"Groovy Server Pages":      "#e69f56",
	"Hack":                     "#878787",
	"Haml":                     "#ece2a9",
	"Handlebars":               "#f7931e",
	"Harbour":                  "#0e60e3",
	"Haskell":                  "#5e5086",
	"Haxe":                     "#df7900",
	"HCL":                      "#613361",
	"HLSL":                     "#aace60",
	"HTML":                     "#e34c26",
	"Hy":                       "#7790B2",
	"HyPhy":                    "#613361",
	"IDL":                      "#a3522f",
	"Idris":                    "#b30000",
	"IGOR Pro":                 "#0000cc",
	"Inform 7":                 "#613361",
	"Inno Setup":               "#264b99",
	"Io":                       "#a9188d",
	"Ioke":                     "#078193",
	"Isabelle":                 "#FEFE00",
	"J":                        "#9EEDFF",
	"Jasmin":                   "#d03600",
	"Java":                     "#b07219",
	"JavaScript":               "#f1e05a",
	"JFlex":                    "#DBCA00",
	"JSONiq":                   "#40d47e",
	"Julia":                    "#a270ba",
	"Jupyter Notebook":         "#DA5B0B",
	"Kotlin":                   "#A97BFF",
	"KRL":                      "#284307",
	"LabVIEW":                  "#fede06",
	"Lasso":                    "#999999",
	"Latte":                    "#f2a542",
	"Lean":                     "#613361",
	"Less":                     "#1d365d",
	"LFE":                      "#4C3023",
	"LiveScript":               "#499886",
	"LLVM":                     "#185619",
	"Logos":                    "#613361",
	"Logtalk":                  "#295b9a",
	"Lolcode":                  "#848bf5",
	"LookML":                   "#652B81",
	"LoomScript":               "#613361",
	"LSL":                      "#3d9970",
	"Lua":                      "#000080",
	"M":                        "#613361",
	"Makefile":                 "#427819",
	"Mako":                     "#7e858d",
	"Markdown":                 "#083fa1",
	"Mask":                     "#f97732",
	"Mathematica":              "#dd1100",
	"Matlab":                   "#e16737",
	"Max":                      "#c4a79c",
	"MAXScript":                "#00a6a6",
	"Mercury":                  "#ff2b2b",
	"Metal":                    "#8f14e9",
	"Mirah":                    "#c7a938",
	"Modelica":                 "#de1d31",
	"Modula-2":                 "#10253f",
	"Module Management System": "#198CE7",
	"Monkey":                   "#613361",
	"Moocode":                  "#613361",
	"MoonScript":               "#613361",
	"MTML":                     "#b7e1f4",
	"MUF":                      "#613361",
	"mupad":                    "#244061",
	"Myghty":                   "#613361",
	"NCL":                      "#28431f",
	"Nemerle":                  "#3d3c6e",
	"nesC":                     "#94B0C7",
	"NetLinx":                  "#0aa0ff",
	"NetLinx+ERB":              "#747faa",
	"NetLogo":                  "#ff6375",
	"NewLisp":                  "#8767ef",
	"Nimrod":                   "#37775b",
	"Nit":                      "#009917",
	"Nix":                      "#7e7eff",
	"Nu":                       "#c9df40",
	"Objective-C":              "#438eff",
	"Objective-C++":            "#6866fb",
	"Objective-J":              "#ff0c5a",
	"OCaml":                    "#3be133",
	"Omgrofl":                  "#cabbff",
	"ooc":                      "#b0b318",
	"Opal":                     "#f7ede0",
	"Oxygene":                  "#cdd0e3",
	"Oz":                       "#fab738",
	"Pan":                      "#cc0000",
	"Papyrus":                  "#6600cc",
	"Parrot":                   "#f3ca0a",
	"Pascal":                   "#E3F171",
	"PAWN":                     "#dbb284",
	"Perl":                     "#0298c3",
	"Perl6":                    "#0000fb",
	"PHP":                      "#4F5D95",
	"PigLatin":                 "#fcd7de",
	"Pike":                     "#005390",
	"PLSQL":                    "#dad8d8",
	"PogoScript":               "#d80074",
	"Processing":               "#0096D8",
	"Prolog":                   "#74283c",
	"Propeller Spin":           "#7fa2a7",
	"Puppet":                   "#302B6D",
	"Pure Data":                "#91de79",
	"PureBasic":                "#5a6986",
	"PureScript":               "#1D222D",
	"Python":                   "#3572A5",
	"QMake":                    "#613361",
	"QML":                      "#44a51c",
	"R":                        "#198CE7",
	"Racket":                   "#22228f",
	"Ragel":                    "#9d5200",
	"RAML":                     "#77d9fb",
	"Rebol":                    "#358a5b",
	"Red":                      "#f50000",
	"Ren'Py":                   "#ff7f7f",
	"Rouge":                    "#cc0088",
	"Ruby":                     "#701516",
	"Rust":                     "#dea584",
	"SaltStack":                "#646464",
	"SAS":                      "#B34936",
	"Scala":                    "#c22d40",
	"Scheme":                   "#1e4aec",
	"Scilab":                   "#ca0f21",
	"SCSS":                     "#c6538c",
	"Self":                     "#0579aa",
	"Shell":                    "#89e051",
	"Shen":                     "#120F14",
	"Slash":                    "#007edc",
	"Slim":                     "#2b2b2b",
	"Smalltalk":                "#596706",
	"SourcePawn":               "#5c7611",
	"SQF":                      "#3F3F3F",
	"SQL":                      "#e38c00",
	"Squirrel":                 "#800000",
	"Standard ML":              "#dc566d",
	"Stata":                    "#1a5f91",
	"Stylus":                   "#ff6347",
	"SuperCollider":            "#463029",
	"Swift":                    "#ffac45",
	"SystemVerilog":            "#DAE1C2",
	"Tcl":                      "#e4cc98",
	"TeX":                      "#3D6117",
	"Turing":                   "#cf142b",
	"TXL":                      "#0178b8",
	"TypeScript":               "#3178c6",
	"Unified Parallel C":       "#4e3617",
	"Unity3D Asset":            "#ab69a1",
	"UnrealScript":             "#a54c4d",
	"Vala":                     "#fbe5cd",
	"Verilog":                  "#b2b7f8",
	"VHDL":                     "#adb2cb",
	"VimL":                     "#199f4b",
	"Visual Basic":             "#945db7",
	"Volt":                     "#1F1F1F",
	"Vue":                      "#41b883",
	"Web Ontology Language":    "#9cc9dd",
	"wisp":                     "#7587a6",
	"X10":                      "#4B6BEF",
	"xBase":                    "#403a40",
	"XC":                       "#99DA07",
	"XML":                      "#0060ac",
	"XProc":                    "#797979",
	"XQuery":                   "#5232e7",
	"XS":                       "#24152y",
	"XSLT":                     "#EB8CEB",
	"Xtend":                    "#24255d",
	"Yacc":                     "#4B6C4B",
	"YAML":                     "#cb171e",
	"Zephir":                   "#118f9e",
	"Zimpl":                    "#d67711",
}
